---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - aws
    - role: jenkins_build
      build_jenkins_server_name: test-jenkins.testeng.edx.org
