build_jenkins_version: jenkins_1.651.3
build_jenkins_war_source: https://s3.amazonaws.com/edx-testeng-tools/jenkins

build_jenkins_debian_pkgs:
  - git
  - curl
  - openjdk-8-jdk
  - nginx
  - maven
  - daemon
  - psmisc

build_jenkins_home: /var/lib/jenkins
build_jenkins_config_path: /init-configs

build_jenkins_configuration_scripts:
  - 1addJarsToClasspath.groovy
  - 2checkInstalledPlugins.groovy
  - 3mainConfiguration.groovy
  - 3shutdownCLI.groovy
  - 4configureEc2Plugin.groovy
  - 4configureGHOAuth.groovy
  - 4configureGHPRB.groovy
  - 4configureGit.groovy
  - 4configureHipChat.groovy
  - 4configureJobConfigHistory.groovy
  - 4configureMailerPlugin.groovy
  - 5addSeedJob.groovy
  - 5createLoggers.groovy
  - 6importCredentials.groovy

# MAIN CONFIG DEFAULT SECRET

BUILD_JENKINS_MAIN_GITHUB_OWNER_WHITELIST: ''

# MAILER CONFIG DEFAULT SECRETS

BUILD_JENKINS_MAILER_SMTP_AUTH_USERNAME: ''
BUILD_JENKINS_MAILER_SMTP_AUTH_PASSWORD: ''

# HIPCHAT CONFIG DEFAULT SECRETS

BUILD_JENKINS_HIPCHAT_API_TOKEN: ''

# EC2 CONFIG DEFAULT SECRETS

BUILD_JENKINS_EC2_PRIVATE_KEY: ''

BUILD_JENKINS_EC2_ACCESS_KEY_ID: ''
BUILD_JENKINS_EC2_SECRET_ACCESS_KEY: ''
BUILD_JENKINS_EC2_IAM_INSTANCE_PROFILE: ''

# GHPRB_CONFIG DEFAULT SECRETS

BUILD_JENKINS_GHPRB_ADMIN_LIST: []


# SECURITY DEFAULT SECRETS

BUILD_JENKINS_SECURITY_CLIENT_ID: ''
BUILD_JENKINS_SECURITY_CLIENT_SECRET: ''
BUILD_JENKINS_SECURITY_EDX_USERS_LIST: []
BUILD_JENKINS_SECURITY_ADMIN_LIST: []
BUILD_JENKINS_SECURITY_BOT_LIST: []
BUILD_JENKINS_SECURITY_CUSTOM_LIST_1: []
BUILD_JENKINS_SECURITY_CUSTOM_LIST_2: []

# CREDENTIALS DEFAULT SECRETS

BUILD_JENKINS_SECRET_FILES_LIST: []
