build_jenkins_debian_pkgs:
  - git
  - curl
  - openjdk-8-jdk
  - nginx
  - maven
  - daemon
  - psmisc

build_jenkins_home: /var/lib/jenkins
build_jenkins_config_path: /init-configs

build_jenkins_configuration_scripts:
  - 1addJarsToClasspath.groovy
  - 2checkInstalledPlugins.groovy
  - 3mainConfiguration.groovy
  - 3shutdownCLI.groovy
  - 4configureEc2Plugin.groovy
  - 4configureGHOAuth.groovy
  - 4configureGHPRB.groovy
  - 4configureGit.groovy
  - 4configureHipChat.groovy
  - 4configureJobConfigHistory.groovy
  - 4configureMailerPlugin.groovy
  - 5addSeedJob.groovy
  - 5createLoggers.groovy
  - 6importCredentials.groovy
