---
dependencies:
  - common
  - role: nginx
    nginx_app_dir: "/etc/nginx"
    nginx_log_dir: "/var/log/nginx"
    nginx_data_dir: "{{ nginx_app_dir }}"
    nginx_conf_dir: "{{ nginx_app_dir }}/conf.d"
    nginx_sites_available_dir: "{{ nginx_app_dir }}/sites-available"
    nginx_sites_enabled_dir: "{{ nginx_app_dir }}/sites-enabled"
    nginx_server_static_dir: "{{ nginx_data_dir }}/server-static"
    nginx_htpasswd_file: "{{ nginx_app_dir }}/nginx.htpasswd"
    nginx_default_sites: "jenkins"
    nginx_template_dir: "etc/nginx/sites-available"
    nginx_sites: jenkins
  - role: oraclejdk
    tags: java
