---
MAIN:
    WORKSPACE_ROOT_DIR: '${ITEM_ROOTDIR}/workspace'
    BUILD_RECORD_ROOT_DIR: '${ITEM_ROOTDIR}/builds'
    SYSTEM_MESSAGE: ''
    NUMBER_OF_EXECUTORS: 3
    LABELS:
        - 'dsl-seed-runner'
        - 'backup-runner'
    USAGE: 'NORMAL'
    QUIET_PERIOD: 5
    SCM_RETRY_COUNT: 0
    DISABLE_REMEMBER_ME: true
GLOBAL_PROPERTIES:
    ENVIRONMENT_VARIABLES:
    TOOL_LOCATIONS:
LOCATION:
    URL: 'https://test-jenkins.testeng.edx.org/'
    ADMIN_EMAIL: 'test-jenkins <test-jenkins@edx.org>'
SHELL:
    EXECUTABLE: '/bin/bash'
CLI:
    CLI_ENABLED: false
