test_jenkins_version: jenkins_1.651.3
test_jenkins_war_source: https://s3.amazonaws.com/edx-testeng-tools/jenkins
test_jenkins_server_name: test-jenkins.testeng.edx.org

test_jenkins_debian_pkgs:
  - git
  - curl
  - nginx
  - maven
  - daemon
  - psmisc

test_jenkins_home: /var/lib/jenkins
test_jenkins_config_path: /init-configs

test_jenkins_configuration_scripts:
  - 1addJarsToClasspath.groovy
  - 2checkInstalledPlugins.groovy
  - 3mainConfiguration.groovy
  - 3shutdownCLI.groovy
  - 4configureEc2Plugin.groovy
  - 4configureGHOAuth.groovy
  - 4configureGHPRB.groovy
  - 4configureHipChat.groovy
  - 4configureJobConfigHistory.groovy
  - 5addSeedJob.groovy
  - 5createLoggers.groovy
  - 6importCredentials.groovy

# MAIN CONFIG DEFAULT SECRET

JENKINS_MAIN_GITHUB_OWNER_WHITELIST: ''

# MAILER CONFIG DEFAULT SECRETS

JENKINS_MAILER_SMTP_AUTH_USERNAME: ''
JENKINS_MAILER_SMTP_AUTH_PASSWORD: ''

# HIPCHAT CONFIG DEFAULT SECRETS

JENKINS_HIPCHAT_API_TOKEN: ''

# EC2 CONFIG DEFAULT SECRETS

JENKINS_EC2_PRIVATE_KEY: ''

JENKINS_EC2_ACCESS_KEY_ID: ''
JENKINS_EC2_SECRET_ACCESS_KEY: ''
JENKINS_EC2_IAM_INSTANCE_PROFILE: ''

# GHPRB_CONFIG DEFAULT SECRETS

JENKINS_GHPRB_TOKEN: ''
JENKINS_GHPRB_ADMIN_LIST: []

# CREDENTIALS DEFAULT SECRETS

JENKINS_SECRET_FILES_LIST: []

# SECURITY DEFAULT SECRETS

TEST_JENKINS_SECURITY_CLIENT_ID: ''
TEST_JENKINS_SECURITY_CLIENT_SECRET: ''
TEST_JENKINS_SECURITY_EDX_USERS_LIST: []
TEST_JENKINS_SECURITY_ADMIN_LIST: []
TEST_JENKINS_SECURITY_BOT_LIST: []
TEST_JENKINS_SECURITY_CUSTOM_LIST_1: []
TEST_JENKINS_SECURITY_CUSTOM_LIST_2: []
