---
- name: Copy config files
  template: src={{ item }} dest='{{ build_jenkins_config_path }}/'
  with_fileglob:
    - '{{ role_path }}/files/*'
  tags:
    - install
    - install:system-requirements

- name: Run plugins.gradle
  shell: './gradlew -b plugins.gradle plugins'
  args:
    chdir: '{{ jenkins_git_home }}/jenkins-configuration'
  environment:
    PLUGIN_OUTPUT_DIR: '{{ build_jenkins_home }}/plugins'
    PLUGIN_CONFIG: '{{ build_jenkins_config_path }}/plugins.yml'

- name: Copy credentials into files
  copy:
    content: "{{ item.content }}"
    dest: '{{ build_jenkins_config_path }}/credentials/{{ item.name }}'
  with_items: '{{ BUILD_JENKINS_SECRET_FILES_LIST }}'