jenkins_user: "jenkins"
jenkins_group: "edx"
jenkins_home: /var/lib/jenkins
jenkins_config_path: /init-configs
jenkins_port: 8080

jenkins_version: jenkins_1.651.3
jenkins_war_source: https://s3.amazonaws.com/edx-testeng-tools/jenkins

jenkins_nginx_port: 80
jenkins_protocol_https: true
jenkins_server_name: "jenkins.testeng.edx.org"

jenkins_debian_pkgs:
  - nginx
  - git
  - curl
  - maven
  - daemon
  - psmisc

jenkins_configuration_scripts: []

jenkins_configuration_git_url: https://github.com/edx/jenkins-configuration.git
jenkins_configuration_src_path: src/main/groovy
jenkins_git_home: /git
